version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: ./backend
    image: 741448955179.dkr.ecr.eu-north-1.amazonaws.com/notes-backend:latest
    pull_policy: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=notes_db
      - DB_PORT=5432
      - PORT=5001
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: 741448955179.dkr.ecr.eu-north-1.amazonaws.com/notes-frontend:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
       - REACT_APP_API_URL=http://backend:5001 
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge