---
name: "A5-devops"

run-name: |
  "devops A5  workflow with devops class triggered by ${{github.actor}}
  with ${{github.event_name}} event
  on branch ${{github.repository}}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint
      - run: cd frontend && npm test
      - run: cd frontend && npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: frontend-build
          path: ./frontend/build/*
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: notes-frontend
          region: eu-north-1
          tags: latest-zoh,${{ github.sha }}
          create_repo: false
          path: ./frontend
          dockerfile: ./frontend/Dockerfile

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: cd backend && npm install
      - run: cd backend && node -c server.js
      - run: cd frontend && node server.js &
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: notes-backend
          region: eu-north-1
          tags: latest-zoh,${{ github.sha }}
          create_repo: false
          path: ./backend
          dockerfile: ./backend/Dockerfile
                                             
  deploy-to-testing-instance:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - uses: actions/checkout@v6
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd dockerize-and-deploy-full-stack-web-app-on-EC2-using-CI-CD-piplines-A5
            git pull origin main
            docker compose -f docker-compose.yml up -d
                       
