


---
name: "A5-devops"

run-name: |
      "devops A5  workflow with devops class triggered by ${{github.actor}}
      with ${{github.event_name}} event
      on branch ${{github.repository}}"


on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint
      - run: cd frontend && npm test
      - run: cd frontend && npm run build
      - uses: actions/upload-artifact@v7 
        with: 
          name: frontend-build
          path: ./frontend/build/*
       


  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: cd backend && npm install
      - run: cd backend && node -c server.js 
      - run: cd frontend && node server.js &
      
